
# Vectorized Backtesting

Making use of vectorization as a useful technical approach to formulating and backtest trading strategies. Here we focus on the following strategies.

- [x] Simple Moving Averages (SMA) Based Strategies
- [x] Momentum Strategies
- [x] Mean Reversion Strategies

N|B The strategies above are not for multifinancial instruments or basket of sevurities.

## Simple Moving Averages (SMA) Based Strategies

SMAs are a major tool for technical analysis of stock price. A signal is derived for example when an SMA defined on a shorter time window -say 42 days- crosses an SMA defined on a longer time window -say 252 days. The rule is <font color='red'>**to go long whenever the shorter SMA is above the longer one and vice-versa**</font>

## Momentum Strategies

These strategies are based on the hypothesis that recent recent performance will persist for an additional time. For example, a stock that is on a downward trend is assumed to do for longer hence the stock should be shorted. This approach introduces backtesting strategies based on the time series momentum (recent/historical performance) of the stock.

## Mean Reversion Strategies

The idea here is that stock prices or prices of other financial instruments tend to revert to some mean level or some trend level where they have deviated too much from such levels.

When it comes to financial analysis/modeling, there are a variety of methods and ways. Just to list a few, we have;
- time series forecasting
- capital asset pricing model
- arbitrage pricing model
- mean portfolio theorem
- Portfolio optimization 
- derivatives i.e option pricing etc 
- and so on

Here we will focus on Vectorization Backtesting where we will look at the strategies discussed above

In [1]:
import numpy as np
import pandas as pd

### Vectorizaton with NumPy

In [2]:
# creating a list of values
v = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
v

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

**Scalar Multiplication in vectorized fashion using List of comprehension**

In [3]:
# trying to multiply each element in the list by 2
v*2

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [4]:
%%time
# using list of comrehension to multiply each element of list v

sm = [i*2 for i in v]
sm

Wall time: 0 ns


[2, 4, 6, 8, 10, 12, 14, 16, 18, 20]

**Scalar Multiplication in vectorized fashion using NumPy**

In [5]:
# Using numpy
a = np.array(v)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
%%time
a * 2

Wall time: 0 ns


array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

**Linear Transformation in vectorized fashion using List of comprehension**

In [7]:
%%time
[(0.5*i + 2) for i in v] #using list of comprehension

Wall time: 0 ns


[2.5, 3.0, 3.5, 4.0, 4.5, 5.0, 5.5, 6.0, 6.5, 7.0]

**Linear Transformation in vectorized fashion using NumPy**

In [8]:
%%time
0.5*a + 2 #using numpy

Wall time: 0 ns


array([2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ])

**Creating 1d ndarray object and reshaping into 2d**

In [9]:
a = np.arange(12)
print(f'Length of array(a) is {len(a)} \nAnd elements of array(a) are {a} \nShape of array(a) is {a.shape} \nThe size of array(a) is {a.size} \nThe dimensions of array(a) is {a.ndim}')
print('\n')
print('Reshaping the array to have 4 rows and 3 columns')
print('...')
a = a.reshape(-1, 3)
print(f'\nLength of array(a) is {len(a)} \nAnd elements of array(a) are {a} \nShape of array(a) is {a.shape} \nThe size of array(a) is {a.size} \nThe dimensions of array(a) is {a.ndim}')

Length of array(a) is 12 
And elements of array(a) are [ 0  1  2  3  4  5  6  7  8  9 10 11] 
Shape of array(a) is (12,) 
The size of array(a) is 12 
The dimensions of array(a) is 1


Reshaping the array to have 4 rows and 3 columns
...

Length of array(a) is 4 
And elements of array(a) are [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]] 
Shape of array(a) is (4, 3) 
The size of array(a) is 12 
The dimensions of array(a) is 2


In [10]:
print(f'The mean for array(a) columns = {np.mean(a, axis=0)} \nMean for array(a) rows = {np.mean(a, axis=1)}')
print('\n')
print(f'\nThe mean for array(a) = {np.mean(a)} \nStandard Deviation = {np.std(a)}')

The mean for array(a) columns = [4.5 5.5 6.5] 
Mean for array(a) rows = [ 1.  4.  7. 10.]



The mean for array(a) = 5.5 
Standard Deviation = 3.452052529534663


### Vectorizaton with Pandas

In [11]:
columns = list('abc')
index = pd.date_range('2021-7-1', periods=4, freq='B') # B stands for business days
print('Columns for our dataframe are: ', columns, '\nIndex for our dataframe: ', index, '\nOur array is, ', a)

Columns for our dataframe are:  ['a', 'b', 'c'] 
Index for our dataframe:  DatetimeIndex(['2021-07-01', '2021-07-02', '2021-07-05', '2021-07-06'], dtype='datetime64[ns]', freq='B') 
Our array is,  [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [12]:
df = pd.DataFrame(a, columns = columns, index=index)
df

a   b   c
2021-07-01  0   1   2
2021-07-02  3   4   5
2021-07-05  6   7   8
2021-07-06  9  10  11

**Scalar Multiplication in vectorized fashion using Pandas**

In [13]:
df*2

a   b   c
2021-07-01   0   2   4
2021-07-02   6   8  10
2021-07-05  12  14  16
2021-07-06  18  20  22

In [14]:
df.sum()

a    18
b    22
c    26
dtype: int64

In [15]:
df.mean()

a    4.5
b    5.5
c    6.5
dtype: float64

In [16]:
df.a + df.c

2021-07-01     2
2021-07-02     8
2021-07-05    14
2021-07-06    20
Freq: B, dtype: int32

**Linear Transformation in vaectorized fashion using NumPy**

In [17]:
0.5 * df.a + 2 * df.b - df.c

2021-07-01     0.0
2021-07-02     4.5
2021-07-05     9.0
2021-07-06    13.5
Freq: B, dtype: float64

In [18]:
df.a > 5

2021-07-01    False
2021-07-02    False
2021-07-05     True
2021-07-06     True
Freq: B, Name: a, dtype: bool

In [19]:
df[df.a > 5]

a   b   c
2021-07-05  6   7   8
2021-07-06  9  10  11

For vectorized backtesting of trading strategies, comparison between two columns are tyoical

In [20]:
df.c > df.b

2021-07-01    True
2021-07-02    True
2021-07-05    True
2021-07-06    True
Freq: B, dtype: bool

In [21]:
df.a + df.b > df.c

2021-07-01    False
2021-07-02     True
2021-07-05     True
2021-07-06     True
Freq: B, dtype: bool